DROP TABLE IF EXISTS series_genres;
DROP TABLE IF EXISTS users_series;
DROP TABLE IF EXISTS episodes;
DROP TABLE IF EXISTS seasons;
DROP TABLE IF EXISTS series;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS users;